package com.flentas.utils;

import org.testng.annotations.DataProvider;

public class ContactFormDataProvider {

	@DataProvider(name = "positiveContactData")
	public static Object[][] getPositiveContactData() {
		return new Object[][] {
				{ "Test QA", "Test.qa@example.com", "flentas", "9876543210",
						"This is a test message generated by automation script." },
				{ "John Doe", "john.doe@example.com", "flentas", "1234567890",
						"Please contact me regarding services. This is a test message generated by automation script." } };
	}

	@DataProvider(name = "negativeContactData")
	public static Object[][] getNegativeContactData() {
		return new Object[][] { { "", "invalid@", "", "000", "" }, { "", "", "", "", "" },
				{ "Test", "Test@", "", "Missing phone", "" },
				{ "Invalid Email", "invalid-email", "Company", "1234567890", "Test" },
				{ "Invalid Name", "test@test.com", "Company", "abc", "Test" } };
	}
}
